name: Publish to VSCODE Marketplace

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-vscode-extension:
    name: Publish VSCode Extension
    uses: Dev-kitx/.github/.github/workflows/vscode-extension-release.yml@main
    secrets: inherit
